In [33]:
import cv2,os
data_path='croped_image'
categories=os.listdir(data_path)
categories


['bad', 'good', 'none']

In [34]:
labels=[i for i in range(len(categories))]
labels


[0, 1, 2]

In [35]:
label_dict=dict(zip(categories,labels))



In [36]:
label_dict

{'bad': 0, 'good': 1, 'none': 2}

In [37]:
print(label_dict)
print(categories)
print(labels)

{'bad': 0, 'good': 1, 'none': 2}
['bad', 'good', 'none']
[0, 1, 2]


In [38]:
img_size=100
data=[]
target=[]


for category in categories:
    folder_path=os.path.join(data_path,category)
    img_names=os.listdir(folder_path)
        
    for img_name in img_names:
        img_path=os.path.join(folder_path,img_name)
        img=cv2.imread(img_path)

        try:
            gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)           
            #Coverting the image into gray scale
            resized=cv2.resize(gray,(img_size,img_size))
            #resizing the gray scale into 100x100, since we need a fixed common size for all the images in the dataset
            data.append(resized)
            target.append(label_dict[category])
            #appending the image and the label(categorized) into the list (dataset)

        except Exception as e:
            print('Exception:',e)
            #if any exception rasied, the exception will be printed here. And pass to the next image

In [39]:
print(target)

[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]


In [40]:
data

[array([[ 28,  28,  27, ...,  32,  32,  32],
        [ 28,  28,  27, ...,  32,  32,  32],
        [ 28,  28,  27, ...,  31,  31,  32],
        ...,
        [175, 175, 177, ...,  99, 102, 103],
        [169, 170, 172, ...,  99, 102, 103],
        [171, 171, 172, ...,  99, 102, 103]], dtype=uint8),
 array([[57, 55, 56, ..., 38, 42, 46],
        [55, 54, 54, ..., 20, 21, 24],
        [53, 52, 52, ...,  8,  6,  8],
        ...,
        [12,  6,  2, ..., 31, 24, 26],
        [15,  9,  4, ..., 32, 26, 28],
        [17, 10,  5, ..., 34, 28, 29]], dtype=uint8),
 array([[ 33,  42,  57, ...,  39,  23,  56],
        [ 26,  53,  42, ...,  29,  32,  76],
        [ 46,  21,  50, ...,  16,  37,  39],
        ...,
        [113, 142, 100, ...,  68,  60,  51],
        [153, 149, 144, ...,  75,  99,  88],
        [108,  91, 150, ...,  62, 110,  72]], dtype=uint8),
 array([[ 21,  20,  25, ..., 119, 219, 137],
        [ 19,  19,  24, ..., 179, 111, 104],
        [ 19,  19,  21, ..., 149, 149, 117],
       

In [41]:
import numpy as np

data=np.array(data)/255.0
data=np.reshape(data,(data.shape[0],img_size,img_size,1))
target=np.array(target)

from keras.utils import np_utils

new_target=np_utils.to_categorical(target)

In [42]:
np.save('test_none_data',data)
np.save('test_none_target',new_target)

In [43]:
#np.save('data',data)
#np.save('target',new_target)